# version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend
    # A volume mount-binds ./backend/app (on host) to /app/app (in container).
    # This means that changes to code in "app" are immediately reflected in 
    # the running container.
    # Useful for development if 'CMD' includes the "--reload" option.
    # This avoids mounting other directories (backend/tests, backend/experiments)
    # in the container. 
    # For production, you should remove this.
    volumes:
      - ./backend/app:/app/app
      - /tmp:/tmp
    # nginx is acting as proxy. For security & architecture, do not expose port 8000.
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PROMETHEUS_MULTIPROC_DIR: /tmp
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-net

  nginx:
    # Nginx web server. Listen on port 8080 on the native host, mapped to port 80 in container.
    # nginx:alpine is smaller than nginx:stable (52MB vs 199MB) and requires less memory.
    # nginx:alpine includes fewer nginx modules, fewer libraries, and musl libc instead of glibc.
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-net

  nginx-exporter:
    # Export server metrics for monitoring via Prometheus.
    # nginx-exporter scrapes metrics from nginx container via a defined endpoint.
    image: nginx/nginx-prometheus-exporter
    container_name: nginx_exporter
    # no need to expose a port
    #ports:
    # - "9113:9113"
    command:
       - '-nginx.scrape-uri=http://nginx:80/nginx_status'
    depends_on:
      - nginx
    networks:
      - app-net

  frontend:
    # Web front-end using Vue.js
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-net

  db:
    # Use PostgreSQL 16+ for UUIDv7 support
    image: postgres:16     
    restart: unless-stopped
    environment:
      # POSTGRES_PASSWORD is required by the image.
      # POSTGRES_USER (superuser name) and POSTGRES_DB override the defaults.
      # PGDATA = define database storage directory within the container (use default).
      # Note: these variables have effect *only if the data directory is empty* (init setup).
      # If data directory already contains files then they have no effect.
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # For Production, do NOT expose a port.
      - "5432:5432"
    volumes:
      # bind mount instructs Docker to copy a file from host to container
      - db_data:/var/lib/postgresql/data
      - ./db/init.d:/docker-entrypoint-initdb.d
    networks:
      - app-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports: 
      - "9090:9090"
    volumes: 
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "472"       # recommended for Grafana container
    ports:
      - "4000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitor/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app-net

volumes:
  db_data:
  grafana_data:
  prometheus_data:

networks:
  app-net:
    driver: bridge

# Containers on the same network (app-net) communicate using the
# *internal container ports* not the host-mapped ports.
# Hence, nginx-exporter scrapes nginx on port 80 instead of 8080.
# They also use internal DNS names, like 'nginx' or 'backend'.
