-- Create tables
-- Create users table. Use INTEGER for id for conciseness at cost of distributed systems.
CREATE TABLE IF NOT EXISTS users (
    id         INTEGER           PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    email      VARCHAR(100)      UNIQUE NOT NULL,
    username   VARCHAR(50),
    created_at TIMESTAMPTZ       DEFAULT CURRENT_TIMESTAMP,
    is_active  BOOLEAN           DEFAULT TRUE
);

-- Create data sources (e.g., water meter, power meter)
CREATE TABLE IF NOT EXISTS data_sources (
    id             INTEGER       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name           TEXT          NOT NULL,
    description    TEXT,
    unit           VARCHAR(20)   NOT NULL,    -- 'kWh', 'cu-m', 'm³'
    created_at     TIMESTAMPTZ   DEFAULT CURRENT_TIMESTAMP,
    created_by     INTEGER       REFERENCES users(id)
);

-- Create measurements table
CREATE TABLE IF NOT EXISTS data_entries (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id      INTEGER     REFERENCES data_sources(id) ON DELETE CASCADE,
    value          NUMERIC     NOT NULL, -- integer or floating point
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by     INTEGER     REFERENCES users(id) -- include for audit trail?
);

-- Optional: index for faster query by timestamp
CREATE INDEX IF NOT EXISTS idx_measurements_timestamp 
          ON data_entries(created_at);

