# Run basic error checking with flake8, then run pytest.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Pytest on backend

on:
  push:
    branches: [ "master", "dev-model-schema" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install pytest flake8
        # requirements-dev.txt includes requirements.txt + packages needed for tests
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Copy testing env-variable values to .env
      run: |
        if [ -f testing.env ]; then cp testing.env .env; fi
    - name: Lint with flake8
      run: |
        cd backend
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd backend
        pytest tests
